version: "3.9"
services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: "always"
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
